#Licence path
#Set path to licence file
#ATTENTION: If you don't have a licence file leave licencePath as it is
#Example: E:/Projects/GroupDocs/app/Resources/Aspose License/GroupDocs.Viewer.Java.lic
licensePath: null

#Server configuration
#Set available ports for application to use
#Example: 
# port: 8080
# adminPort: 8081
http:
  port: 8080
  adminPort: 8081

#Application Path
#This path used in application for sending request
applicationPath: http://127.0.0.1:8080
  
#Files path
#Set root path for files and images
#ATTENTION: Root path should contain files
#Example: E:/Projects/GroupDocs/
assets:
  overrides:
    /assets: E:/Projects/GroupDocs/app/xFiles
  mimeTypes:
    woff: application/font-woff

#Authorization
#Set true ONLY if viewer requests will be overridden for authorization
useAuthorization: false

#File expiration date
#File upload expiration date in minutes
#Set to 0 if file is never expired
expirationDate: 5

#Cache
#Use cache generated files
useCache: true

#Encryption key
#NOTE: key must be 16 characters long!
encryptionKey: GroupDocsEncrypt

#*******************************
# FRONT-END (UI) CONFIGURATION
#*******************************

#HTML output
#If true all documents will be converted to HTML instead of images
#ATTENTION: if this flag is set to 'true' useCache flag should be 'true' as well
useHtmlBasedEngine: true

#Quality
#Default quality of generated images
quality: 100

#Show thumbnails
showThumbnails: true

#Open thumbnails
openThumbnails: true

#Initial zoom
initialZoom: 100

#Zoom to fit width
zoomToFitWidth: true

#Zoom to fit height
zoomToFitHeight: false

#Width
#Viewer width
width: 1000

#Height
#Viewer height
height: 650

#Background color
#NOTE: leave empty for default
backgroundColor:

#Show folder browser button
showFolderBrowser: true

#Show print button
showPrint: true

#Show download button
showDownload: true

#Show zoom button
showZoom: true

#Show paging
showPaging: true

#Show viewer style control
showViewerStyleControl: true

#Show search
showSearch: true

#Pre-load pages count
preloadPagesCount: 0

#Viewer style
viewerStyle: 1

#Support text selection
supportTextSelection: true

#Use pdf printing
usePdfPrinting: false

#Toolbar buttons box shadow style
#NOTE: leave empty for default
toolbarButtonsBoxShadowStyle:

#Toolbar buttons box shadow hover style
#NOTE: leave empty for default
toolbarButtonsBoxShadowHoverStyle:

#Thumbnails container background color
#NOTE: leave empty for default
thumbnailsContainerBackgroundColor:

#Thumbnails container border right color
#NOTE: leave empty for default
thumbnailsContainerBorderRightColor:

#Toolbar border bottom color
#NOTE: leave empty for default
toolbarBorderBottomColor:

#Toolbar input field border color
#NOTE: leave empty for default
toolbarInputFieldBorderColor:

#Toolbar button border color
#NOTE: leave empty for default
toolbarButtonBorderColor:

#Toolbar button border hover color
#NOTE: leave empty for default
toolbarButtonBorderHoverColor:

#Thumbnails container width
#NOTE: minimum 0
thumbnailsContainerWidth: 0

#Show download errors in popup
showDownloadErrorsInPopup: false

#Show image width
showImageWidth: false

#Show header
showHeader: true

#Minimum image width
minimumImageWidth: 0

#Enable standard error handling
enableStandardErrorHandling: true

#Use image based printing
useImageBasedPrinting: true

#Download file as PDF
downloadPdfFile: false

#Search for separate words
searchForSeparateWords: false

#preventTouchEventsBubbling
preventTouchEventsBubbling: false

#Use innet thumbnails
useInnerThumbnails: true

#Watermark text
# NOTE: leave empty if there is no need in watermark text
watermarkText:

#Support page re-ordering
supportPageReordering: false