#Licence Path
#Set path to licence file
#ATTENTION: If you don't have a licence file leave licencePath as it is
#Example: E:\\Projects\\GroupDocs\\app\\Resources\\Aspose License\\GroupDocs.Viewer.Java.lic
licensePath: null

#Server configuration
#Set available ports for application to use
#Example: 
# port: 8080
# adminPort: 8081
http:
  port: 8080
  adminPort: 8081

#Application Path
#This path used in application for sending request
applicationPath: http://127.0.0.1:8080
  
#Authorization
#Set true ONLY if viewer requests will be overridden for authorization
useAuthorization: false

#Cache
#Use cache generated files
useCache: true

#File expiration date
#File upload expiration date in minutes
#Set to 0 if file is never expired
expirationDate: 5

#Files path
#Set root path for files and images
#ATTENTION: Root path should contain images, files and licence folders
#Example: E:/Projects/GroupDocs/
assets:
  overrides:
    /assets: E:\Projects\GroupDocs\app\xFiles
  mimeTypes:
    woff: application/font-woff

quality: 100

showThumbnails: true

openThumbnails: true

initialZoom: 100

zoomToFitWidth: true

zoomToFitHeight: false

width: 1000

height: 650

showFolderBrowser: true

showPrint: true

showDownload: true

showZoom: true

showPaging: true

showViewerStyleControl: true

showSearch: true

preloadPagesCount: 0

supportTextSelection: true

usePdfPrinting: false

showHeader: true

useHtmlBasedEngine: true

useInnerThumbnails: true